apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - image: gcr.io/kaniko-project/executor:v1.23.2-debug
    imagePullPolicy: Always
    name: kaniko
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: cache
      mountPath: /images
    - name: jenkins-docker-cfg
      mountPath: /kaniko/.docker
  volumes:
  - name: cache
    persistentVolumeClaim:
      claimName: image-cache
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
         name: ugd-registry
         items:
         - key: .dockerconfigjson
           path: config.json

---
apiVersion: v1
kind: Pod
metadata:
  name: trivy
spec:
  containers:
  - image: bitnami/trivy:latest
    imagePullPolicy: Always
    name: trivy
    command:
    - sleep
    args:
    - 99d



